package com.example.dancingwikiapp


data class Movement(
    val id: Int,
    val name_official: String,
    val synonyms: List<String>,
    val description: String,
    val grade: Int,
    val complexity: Int,
    val typo: String,
    val translation: String,
    val detailed_description: String,
    val related: List<String>,
    val methodical_description: String,
    val child_explanation: String
) : Searchable {

    override fun doesMatchSearchQuery(query: String): Boolean {
        val matchingCombinations = listOf(name_official, typo, "${name_official.first()}") + synonyms
        return matchingCombinations.any { it.contains(query, ignoreCase = true) }
    }
}








// Movimentos até a Grade 3 com conceitos relacionados
val Movements = listOf(
    Movement(
        id = 1,
        name_official = "Plié",
        synonyms = listOf("Dobrar", "Flexionar"),
        description = "Flexão dos joelhos em várias posições, foco em postura e alinhamento.",
        grade = 1,
        complexity = 1,
        typo = "Plie",
        translation = "Flexão",
        detailed_description = "O plié é um movimento fundamental no balé onde o dançarino dobra os joelhos enquanto mantém a postura ereta. Ele pode ser feito em várias posições dos pés, como primeira e segunda. A execução correta do plié ajuda a melhorar a flexibilidade, o alinhamento e o controle dos movimentos.",
        related = listOf("Postura", "Alinhamento", "Flexibilidade", "Controle dos joelhos"),
        methodical_description = "Para executar o plié, dobre os joelhos lentamente, mantendo a postura ereta e os pés na posição desejada. Certifique-se de que seus joelhos se movam diretamente para frente e que seu torso permaneça alinhado. O plié pode ser feito em várias posições dos pés, sempre focando na manutenção da postura correta e do alinhamento.",
        child_explanation = "No plié, você se agacha um pouquinho, dobrando os joelhos, enquanto fica em uma posição de balé. Pense em como se estivesse se abaixando suavemente para pegar algo no chão e depois voltando para cima, sempre mantendo uma postura bonita."
    ),
    Movement(
        id = 2,
        name_official = "Tendu",
        synonyms = listOf("Estender", "Alongar"),
        description = "Movimento de extensão do pé no chão, frente, lado e trás.",
        grade = 1,
        complexity = 1,
        typo = "Tendu",
        translation = "Estender",
        detailed_description = "O tendu é um movimento onde o pé é estendido para frente, para o lado ou para trás, mantendo o contato com o chão. Esse movimento desenvolve a força, a flexibilidade e o controle dos músculos das pernas e dos pés. É fundamental para preparar a perna para movimentos mais complexos.",
        related = listOf("Controle do pé", "Flexibilidade das pernas", "Força dos músculos das pernas"),
        methodical_description = "Para realizar o tendu, estique a perna ao longo do chão, mantendo o contato constante do pé com o solo. Comece a partir de uma posição inicial, deslize a perna estendida para frente, lado ou trás, certificando-se de que a extensão seja limpa e controlada. Mantenha o corpo alinhado e o pé ativo.",
        child_explanation = "No tendu, você estica a perna no chão, como se estivesse empurrando algo com o pé, mas sem levantar o pé do chão. Imagine que seu pé está tentando alcançar um lugar bem distante, mas continua tocando o chão."
    ),
    Movement(
        id = 3,
        name_official = "Dégagé",
        synonyms = listOf("Levantar", "Soltar o pé"),
        description = "Movimento onde o pé se levanta ligeiramente do chão.",
        grade = 1,
        complexity = 1,
        typo = "Degage",
        translation = "Desprendido",
        detailed_description = "No dégagé, o pé se levanta ligeiramente do chão, criando um pequeno espaço entre o pé e o solo. Esse movimento é usado para desenvolver a velocidade e a precisão dos pés, além de ajudar na transição para movimentos mais complexos e saltos.",
        related = listOf("Precisão dos pés", "Velocidade", "Transição entre movimentos"),
        methodical_description = "Para executar o dégagé, levante o pé ligeiramente do chão, criando um espaço pequeno entre o pé e o solo. Mantenha o movimento rápido e preciso, focando em como o pé se move para fora e retorna ao chão. Esse exercício deve ser feito com controle e atenção à velocidade e à precisão.",
        child_explanation = "No dégagé, você levanta o pé um pouquinho do chão e depois o coloca de volta. É como se estivesse tentando fazer um pequeno pulo no chão com o pé, mas sem sair muito do lugar."
    ),
    Movement(
        id = 4,
        name_official = "Rond de Jambe à Terre",
        synonyms = listOf("Círculo de perna no chão"),
        description = "Desenhar círculos com a perna no chão, exige controle do quadril.",
        grade = 1,
        complexity = 2,
        typo = "Rond de Jambe a Terre",
        translation = "Círculo de perna no chão",
        detailed_description = "O rond de jambe à terre envolve o movimento da perna em um círculo ao longo do chão, tanto para frente quanto para trás. Esse exercício ajuda a melhorar a flexibilidade e a mobilidade do quadril e a fortalecer os músculos ao redor da articulação do quadril.",
        related = listOf("Mobilidade do quadril", "Flexibilidade", "Controle da perna"),
        methodical_description = "Para realizar o rond de jambe à terre, mova a perna em um círculo no chão, começando para frente e depois para trás. Mantenha o pé em contato com o chão durante todo o movimento e certifique-se de que o círculo seja suave e controlado. O exercício deve ser feito com atenção ao controle do quadril e à flexibilidade.",
        child_explanation = "No rond de jambe à terre, você faz um círculo com a perna no chão, como se estivesse desenhando um círculo no chão com o pé. É como fazer um movimento redondo com a perna, enquanto o pé continua tocando o chão."
    ),
    Movement(
        id = 5,
        name_official = "Sauté",
        synonyms = listOf("Salto"),
        description = "Pequenos saltos no lugar, geralmente na primeira ou segunda posição.",
        grade = 1,
        complexity = 1,
        typo = "Saute",
        translation = "Salto",
        detailed_description = "O sauté é um salto simples onde o dançarino se eleva do chão e retorna rapidamente. É um movimento fundamental para desenvolver a força das pernas, a coordenação e o controle ao aterrissar. O sauté pode ser realizado em várias posições dos pés, como primeira e segunda.",
        related = listOf("Força das pernas", "Coordenação", "Controle ao aterrissar"),
        methodical_description = "Para executar o sauté, eleve-se do chão rapidamente e retorne de volta com um controle preciso. Mantenha o corpo alinhado e a posição dos pés correta durante o salto. Esse movimento deve ser feito com força nas pernas e atenção ao aterrissar suavemente.",
        child_explanation = "No sauté, você dá um pequeno pulo no lugar, como se estivesse tentando tocar algo no ar e depois voltar rapidamente para baixo. É como um pequeno salto que você faz sem se mover para frente ou para trás."
    ),
    Movement(
        id = 6,
        name_official = "Relevé",
        synonyms = listOf("Elevar"),
        description = "Elevar-se nas pontas dos pés, trabalhando o equilíbrio.",
        grade = 1,
        complexity = 2,
        typo = "Releve",
        translation = "Elevado",
        detailed_description = "O relevé é o movimento onde o dançarino se levanta sobre as pontas dos pés, mantendo o corpo alinhado. Esse exercício fortalece os músculos das pernas e melhora o equilíbrio. É frequentemente usado como preparação para pirouettes e outros movimentos em relevé.",
        related = listOf("Equilíbrio", "Força dos músculos das pernas", "Postura"),
        methodical_description = "Para realizar o relevé, eleve-se sobre as pontas dos pés mantendo o corpo alinhado e a postura ereta. O movimento deve ser feito com controle para garantir que o equilíbrio seja mantido e que o corpo não se incline para frente ou para trás.",
        child_explanation = "No relevé, você fica em pé nas pontas dos pés, como se estivesse tentando alcançar algo bem alto com seus pés. É como se estivesse fazendo um esforço para ficar bem em cima das pontas dos pés sem balançar."
    ),
    Movement(
        id = 7,
        name_official = "Échappé Sauté",
        synonyms = listOf("Abrir e fechar no salto"),
        description = "Salto onde os pés se afastam e depois se fecham.",
        grade = 1,
        complexity = 2,
        typo = "Echappe Saute",
        translation = "Salto escapado",
        detailed_description = "O échappé sauté é um salto onde o dançarino abre os pés em uma posição e os fecha novamente ao aterrissar. Esse movimento trabalha a coordenação e a agilidade, além de melhorar o controle dos movimentos ao abrir e fechar os pés no ar.",
        related = listOf("Coordenação", "Agilidade", "Controle dos pés"),
        methodical_description = "Para executar o échappé sauté, salte e abra os pés em uma posição, depois feche-os novamente ao aterrissar. Mantenha o movimento controlado e  preciso, focando na transição suave entre abrir e fechar os pés.",
        child_explanation = "No échappé sauté, você pula e abre os pés no ar, depois fecha os pés quando está voltando para o chão. É como se estivesse abrindo as pernas para um salto e depois fechando-as quando você volta para baixo."
    ),
    Movement(
        id = 8,
        name_official = "Balancé",
        synonyms = listOf("Balançar", "Oscilar"),
        description = "Movimento que oscila entre dois lados, pode ser em três tempos.",
        grade = 2,
        complexity = 2,
        typo = "Balance",
        translation = "Oscilar",
        detailed_description = "O balancé é um movimento de oscilação onde o dançarino se move de um lado para o outro em três tempos. Esse movimento desenvolve a coordenação e a fluidez, além de melhorar a capacidade de transição entre diferentes posições.",
        related = listOf("Coordenação", "Fluidez", "Transições"),
        methodical_description = "Para realizar o balancé, mova-se de um lado para o outro em três tempos, mantendo um ritmo constante e fluido. Certifique-se de que o movimento seja equilibrado e controlado, com transições suaves entre cada passo.",
        child_explanation = "No balancé, você balança de um lado para o outro, como se estivesse fazendo uma dança suave e fluida. É como um movimento de oscilação, onde você vai para um lado e depois para o outro, mantendo o ritmo."
    ),
    Movement(
        id = 9,
        name_official = "Chassé",
        synonyms = listOf("Deslizar", "Escorregar"),
        description = "Deslizar o pé de uma posição para outra, geralmente em movimento.",
        grade = 2,
        complexity = 2,
        typo = "Chasse",
        translation = "Deslizar",
        detailed_description = "O chassé é um movimento onde o pé desliza de uma posição para outra, geralmente em movimento. É um passo usado para criar fluidez na dança e para transitar entre diferentes posições. O chassé pode ser realizado em várias direções e velocidades.",
        related = listOf("Fluidez", "Transições", "Movimento"),
        methodical_description = "Para executar o chassé, deslize um pé para a frente, lado ou atrás, enquanto o outro pé segue em direção ao primeiro. Mantenha o movimento suave e controlado, focando na transição fluida entre as posições.",
        child_explanation = "No chassé, você desliza o pé para frente ou para o lado, como se estivesse escorregando no chão. É como um movimento de deslizamento, onde um pé vai na frente e o outro o segue suavemente."
    ),
    Movement(
        id = 10,
        name_official = "Pas de Bourrée",
        synonyms = listOf("Passo de Bourrée", "Passo de Dança"),
        description = "Três passos rápidos, pode ser para frente, para trás ou para o lado.",
        grade = 2,
        complexity = 2,
        typo = "Pas de Bourree",
        translation = "Passo de Bourrée",
        detailed_description = "O pas de bourrée é um movimento onde o dançarino faz três passos rápidos em uma sequência. Pode ser realizado para frente, para trás ou para o lado. Esse movimento é usado para criar ritmo e fluidez na dança, além de melhorar a coordenação e a agilidade.",
        related = listOf("Ritmo", "Fluidez", "Coordenação"),
        methodical_description = "Para realizar o pas de bourrée, dê três passos rápidos em sequência, movendo-se para frente, para trás ou para o lado. Certifique-se de que o movimento seja ágil e controlado, mantendo um ritmo constante e fluido.",
        child_explanation = "No pas de bourrée, você dá três passos rápidos, indo para frente, para trás ou para o lado. Imagine que você está fazendo um movimento rápido e divertido, como se estivesse pulando de um lugar para outro."
    ),
    Movement(
        id = 11,
        name_official = "Glissade",
        synonyms = listOf("Deslizar", "Escorregar"),
        description = "Movimento de deslizar uma perna para fora, geralmente seguido de um salto.",
        grade = 2,
        complexity = 2,
        typo = "Glissade",
        translation = "Deslizar",
        detailed_description = "O glissade é um movimento onde uma perna desliza para fora, geralmente seguido de um salto. É usado para criar fluidez e transição entre diferentes posições, além de melhorar a força e a coordenação.",
        related = listOf("Fluidez", "Força", "Coordenação"),
        methodical_description = "Para executar o glissade, deslize uma perna para fora e depois execute um salto, retornando à posição inicial. Mantenha o movimento suave e controlado, focando na fluidez entre o deslizar e o salto.",
        child_explanation = "No glissade, você desliza a perna para fora e depois faz um pequeno salto. É como se estivesse escorregando no chão e depois pulando um pouquinho, como um movimento fluido e suave."
    ),
    Movement(
        id = 12,
        name_official = "Pirouette",
        synonyms = listOf("Giro", "Rodopio"),
        description = "Giro sobre uma perna, exigindo equilíbrio e controle.",
        grade = 3,
        complexity = 3,
        typo = "Pirouet",
        translation = "Giro",
        detailed_description = "A pirouette é um giro sobre uma perna, onde o dançarino deve manter o equilíbrio e o controle durante toda a rotação. É um movimento avançado que requer força, técnica e prática para ser executado corretamente.",
        related = listOf("Equilíbrio", "Técnica", "Controle"),
        methodical_description = "Para realizar uma pirouette, fique sobre uma perna e gire em torno do eixo vertical, mantendo o equilíbrio e o controle. Use o outro pé e os braços para ajudar a manter o giro e a estabilidade durante a rotação.",
        child_explanation = "Na pirouette, você faz um giro em cima de uma perna, como se estivesse rodopiando em um lugar. Imagine girar como uma bailarina em um palco, mantendo o equilíbrio enquanto você gira."
    ),
    Movement(
        id = 13,
        name_official = "Fondu",
        synonyms = listOf("Amolecer", "Dobra"),
        description = "Flexão da perna de apoio enquanto a outra está levantada.",
        grade = 3,
        complexity = 3,
        typo = "Fondue",
        translation = "Amolecer",
        detailed_description = "O fondu é um movimento onde a perna de apoio se flexiona enquanto a outra perna está levantada. Esse movimento é usado para desenvolver a força e o controle da perna de apoio, além de melhorar a coordenação e a fluidez dos movimentos.",
        related = listOf("Força da perna de apoio", "Coordenação", "Controle"),
        methodical_description = "Para executar o fondu, flexione a perna de apoio enquanto a outra perna está levantada, mantendo o controle e o equilíbrio. Certifique-se de que o movimento seja fluido e que a perna de apoio suporte o peso de maneira adequada.",
        child_explanation = "No fondu, você dobra a perna que está no chão, enquanto a outra perna está levantada. É como se estivesse se abaixando um pouco com uma perna e mantendo a outra perna no ar."
    ),
    Movement(
        id = 14,
        name_official = "Assemblé",
        synonyms = listOf("Juntar", "Reunir"),
        description = "Salto onde os pés se juntam no ar e aterrissam juntos.",
        grade = 3,
        complexity = 3,
        typo = "Assemble",
        translation = "Juntar",
        detailed_description = "O assemblé é um salto onde os pés se juntam no ar e aterrissam juntos. Esse movimento exige coordenação e controle para garantir que os pés se juntem corretamente durante o salto e que a aterrissagem seja suave.",
        related = listOf("Coordenação", "Controle", "Aterrissagem"),
        methodical_description = "Para executar o assemblé, salte e junte os pés no ar, garantindo que se encontrem e se mantenham juntos antes de aterrissar. Mantenha o movimento controlado e a aterrissagem suave, com os pés unidos.",
        child_explanation = "No assemblé, você dá um salto e junta os pés no ar, como se estivesse tentando tocar os pés com as mãos. Depois, você aterrissa com os pés juntinhos no chão."
    ),
    Movement(
        id = 15,
        name_official = "Sissonne",
        synonyms = listOf("Pular", "Saltitar"),
        description = "Salto onde um pé é levantado enquanto o outro permanece no chão.",
        grade = 3,
        complexity = 3,
        typo = "Sissone",
        translation = "Saltitar",
        detailed_description = "A sissonne é um salto onde um pé é levantado enquanto o outro permanece no chão. Esse movimento é usado para desenvolver a força e o controle dos saltos, além de melhorar a capacidade de transição entre diferentes posições.",
        related = listOf("Força dos saltos", "Controle", "Transição"),
        methodical_description = "Para realizar a sissonne, salte levantando um pé e mantendo o outro no chão, e depois retorne à posição inicial. Mantenha o controle e a força durante o salto, focando na transição suave entre as posições.",
        child_explanation = "Na sissonne, você pula levantando um pé e mantendo o outro no chão, como se estivesse fazendo um salto onde um pé vai para cima e o outro fica no chão. Depois você volta para a posição inicial."
    ),
    Movement(
        id = 16,
        name_official = "Grand Jeté",
        synonyms = listOf("Salto Grande", "Salto Lateral"),
        description = "Salto grande onde as pernas são esticadas no ar.",
        grade = 4,
        complexity = 4,
        typo = "Grand Jete",
        translation = "Salto Grande",
        detailed_description = "O grand jeté é um salto grande onde as pernas são esticadas no ar, criando uma forma de linha reta ou quase reta. Esse movimento exige grande força e controle, além de uma técnica precisa para garantir que as pernas estejam bem esticadas e a aterrissagem seja suave.",
        related = listOf("Força", "Controle", "Técnica"),
        methodical_description = "Para executar o grand jeté, dê um salto grande e estique as pernas no ar, mantendo-as alinhadas. Concentre-se na força necessária para o salto e na técnica para garantir uma aterrissagem suave.",
        child_explanation = "No grand jeté, você faz um salto grande e estica as pernas no ar, como se estivesse tentando alcançar algo bem longe. Depois, você aterrissa suavemente no chão, como se estivesse fazendo um salto bem grandão."
    ),
    Movement(
        id = 17,
        name_official = "Développé",
        synonyms = listOf("Desenvolver", "Levantar"),
        description = "Levantamento da perna estendida para a frente, lado ou atrás.",
        grade = 4,
        complexity = 4,
        typo = "Developpe",
        translation = "Desenvolver",
        detailed_description = "O développé é um movimento onde a perna é levantada e estendida para a frente, lado ou atrás. Esse movimento é usado para melhorar a flexibilidade e o controle das pernas, além de desenvolver a força e a técnica necessárias para a execução correta.",
        related = listOf("Flexibilidade", "Controle", "Força"),
        methodical_description = "Para realizar o développé, levante a perna estendida para a frente, lado ou atrás, mantendo o controle e a técnica adequada. Concentre-se na flexibilidade e na força para garantir uma execução suave e precisa.",
        child_explanation = "No développé, você levanta a perna estendida para a frente, lado ou atrás, como se estivesse tentando alcançar algo com a perna. É como um movimento de levantar a perna, mantendo-a esticada."
    ),
    Movement(
        id = 18,
        name_official = "Fouetté",
        synonyms = listOf("Balanço", "Giro Rápido"),
        description = "Movimento giratório rápido onde uma perna gira em torno do eixo.",
        grade = 4,
        complexity = 4,
        typo = "Fouette",
        translation = "Balanço",
        detailed_description = "O fouetté é um movimento giratório rápido onde uma perna gira em torno do eixo enquanto a outra permanece na posição inicial. Esse movimento exige grande controle e técnica, além de um bom senso de equilíbrio e coordenação.",
        related = listOf("Controle", "Coordenação", "Equilíbrio"),
        methodical_description = "Para executar o fouetté, gire rapidamente com uma perna enquanto a outra permanece na posição inicial. Concentre-se no controle e na técnica para manter o equilíbrio e a coordenação durante o giro.",
        child_explanation = "No fouetté, você gira rapidamente com uma perna enquanto a outra perna fica parada. É como um movimento de giro rápido, onde você balança uma perna e a outra ajuda a manter o equilíbrio."
    ),
    Movement(
        id = 19,
        name_official = "Battement Tendu",
        synonyms = listOf("Battement à Terre", "Battement Tendu à Terre"),
        description = "Extensão da perna em direção ao chão, frente, lado ou trás.",
        grade = 1,
        complexity = 1,
        typo = "Battement Tendu",
        translation = "Battement Estendido",
        detailed_description = "O battement tendu é uma extensão da perna, do pé, ao longo do chão, geralmente para frente, para o lado ou para trás, enquanto se mantém o contato com o chão. É um movimento fundamental que ajuda a construir a flexibilidade, a força e o controle dos músculos das pernas e dos pés.",
        related = listOf("Flexibilidade", "Força", "Controle", "Pés", "Perna"),
        methodical_description = "Comece em uma posição de base, como a primeira posição. Estenda a perna ao longo do chão, mantendo o pé em contato com o solo. Mantenha a postura ereta e o centro do corpo firme. Mova a perna de volta para a posição inicial com controle. O battement tendu pode ser realizado em várias direções e velocidades.",
        child_explanation = "Imagine que você está empurrando algo com seu pé, mas não está levantando o pé do chão. É como se estivesse esticando a perna no chão."
    ),
    Movement(
        id = 20,
        name_official = "Demi-Plié",
        synonyms = listOf("Meio Plié"),
        description = "Flexão dos joelhos a meio caminho da posição de plié completo.",
        grade = 1,
        complexity = 1,
        typo = "Demi-Plié",
        translation = "Meio Plié",
        detailed_description = "O demi-plié é uma flexão parcial dos joelhos, onde os joelhos são dobrados até a metade da posição de plié completo. É um movimento de preparação para o plié completo e também um importante exercício para desenvolver a força e o controle dos músculos das pernas e dos pés.",
        related = listOf("Força", "Controle", "Pés", "Perna", "Plié"),
        methodical_description = "Comece em uma posição de base, como a primeira posição. Dobre os joelhos até a metade da posição de plié completo, mantendo o corpo ereto e o centro do corpo firme. Mantenha a linha dos pés e evite que os joelhos se desviem para dentro. Retorne à posição inicial com controle.",
        child_explanation = "É como um plié, mas você só dobra os joelhos até a metade! É um meio caminho para um plié completo."
    ),
    Movement(
        id = 21,
        name_official = "Port de Bras",
        synonyms = listOf("Carriage of the Arms"),
        description = "Movimentos e posições dos braços, controlados e expressivos.",
        grade = 1,
        complexity = 1,
        typo = "Port de Bras",
        translation = "Porte dos Braços",
        detailed_description = "O port de bras se refere aos movimentos e posições dos braços em balé, e é essencial para a expressão, graça e equilíbrio. O port de bras é usado para adicionar fluidez e beleza à dança, e é um importante elemento para a comunicação da música e das emoções.",
        related = listOf("Braços", "Expressão", "Graça", "Equilíbrio", "Fluidez", "Comunicação"),
        methodical_description = "Comece com os braços em uma posição inicial, como a primeira posição de braço. Mova os braços em um movimento suave e controlado, mantendo uma postura ereta e um centro do corpo firme. Explore diferentes formas e posições dos braços, mantendo a consciência do fluxo e da expressividade.",
        child_explanation = "É como fazer desenhos no ar com os braços, enquanto se mantém uma postura elegante e bonita."
    ),
    Movement(
        id = 22,
        name_official = "Petits Jetés",
        synonyms = listOf("Small Jumps"),
        description = "Pequenos saltos onde o dançarino se eleva ligeiramente do chão.",
        grade = 1,
        complexity = 1,
        typo = "Petits Jetés",
        translation = "Pequenos Saltos",
        detailed_description = "O petit jeté é um pequeno salto onde o dançarino se eleva ligeiramente do chão. É um movimento fundamental que ajuda a desenvolver a força das pernas, a coordenação e o controle ao aterrissar. Os petits jetés podem ser feitos em várias direções, incluindo para frente, para trás e para o lado.",
        related = listOf("Força", "Controle", "Coordenação", "Salto", "Pernas", "Aterrissagem"),
        methodical_description = "Comece em uma posição de base. Eleve-se ligeiramente do chão com um salto rápido e controlado. Mantenha o corpo alinhado durante o salto e a aterrissagem. Pratique o petit jeté em várias direções para aumentar a coordenação e o controle.",
        child_explanation = "É como um pequeno salto, onde você apenas levanta os pés do chão por um instante. Imagine que você está pulando um pouco para chegar a algo que está logo ali na sua frente."
    ),
    Movement(
        id = 23,
        name_official = "Spring Points",
        synonyms = listOf("Springing Points"),
        description = "Saltos para a frente, para o lado ou para trás, com uma pequena elevação do corpo.",
        grade = 1,
        complexity = 1,
        typo = "Spring Points",
        translation = "Pontos de Pulo",
        detailed_description = "O spring point é um salto rápido e elástico, geralmente realizado em uma posição de base. O dançarino se eleva ligeiramente do chão, mantendo o corpo alinhado, e aterrissa na mesma posição. É um movimento fundamental para desenvolver a força das pernas, a coordenação e o controle ao aterrissar.",
        related = listOf("Força", "Controle", "Coordenação", "Salto", "Pernas", "Aterrissagem"),
        methodical_description = "Comece em uma posição de base. Salte com um movimento rápido e elástico, mantendo o corpo alinhado e aterrissando na mesma posição. Repita o movimento em várias direções, como para frente, para o lado e para trás, para desenvolver a coordenação e a fluidez.",
        child_explanation = "Imagine que você está pulando em um trampolim, mas só se elevando um pouquinho do chão. É como um pequeno salto que você faz com uma explosão de energia."
    ),
    Movement(
        id = 24,
        name_official = "Galop",
        synonyms = listOf("Gallop"),
        description = "Movimento rápido de três tempos que imita a passada de um cavalo.",
        grade = 1,
        complexity = 2,
        typo = "Galop",
        translation = "Galope",
        detailed_description = "O galop é um movimento de três tempos que imita a passada de um cavalo. É um movimento de ritmo rápido que requer coordenação e controle. O galop é frequentemente usado em danças de caráter e em algumas sequências de balé clássico.",
        related = listOf("Ritmo", "Coordenação", "Controle", "Pernas", "Movimento", "Danças de caráter"),
        methodical_description = "O galop é realizado em três tempos. Primeiro, o dançarino se move para frente com uma perna. Em seguida, a outra perna é trazida para a frente e se junta à primeira perna. Finalmente, a primeira perna é movida para frente, completando o ciclo. Mantenha o corpo alinhado e o movimento fluido.",
        child_explanation = "Imagine que você está montando um cavalo e se movendo rápido! É como um movimento de três passos, onde você coloca um pé à frente, depois o outro, e depois o primeiro novamente."
    ),
    Movement(
        id = 25,
        name_official = "Battement  à la seconde",
        synonyms = listOf("Battement à la Seconde", "Battement to the Second Position"),
        description = "Extensão da perna para o lado em uma posição de segunda posição.",
        grade = 2,
        complexity = 2,
        typo = "Battement  à la seconde",
        translation = "Battement à la Seconde",
        detailed_description = "O battement à la seconde é um movimento onde a perna é estendida para o lado, formando a segunda posição, e depois é movida de volta à posição inicial. É um exercício fundamental para desenvolver a flexibilidade, a força e o controle dos músculos das pernas e dos pés.",
        related = listOf("Flexibilidade", "Força", "Controle", "Pés", "Perna", "Segunda Posição"),
        methodical_description = "Comece em uma posição de base, como a primeira posição. Estenda a perna para o lado, mantendo o pé em contato com o solo. Mantenha a postura ereta e o centro do corpo firme. Mova a perna de volta para a posição inicial com controle. O battement à la seconde pode ser realizado em várias velocidades e níveis de elevação.",
        child_explanation = "É como um battement tendu, mas você estende a perna até que ela fique bem na posição de segunda posição."
    ),
    Movement(
        id = 26,
        name_official = "Grand Battement",
        synonyms = listOf("Grande Battement"),
        description = "Extensão da perna para cima, frente, lado ou trás.",
        grade = 2,
        complexity = 3,
        typo = "Grand Battement",
        translation = "Grande Battement",
        detailed_description = "O grand battement é uma extensão da perna para cima, frente, lado ou trás, formando uma forma de V. É um movimento avançado que requer flexibilidade, força e controle. O grand battement é frequentemente usado em sequências de balé clássico e em danças de caráter.",
        related = listOf("Flexibilidade", "Força", "Controle", "Pés", "Perna", "V Position"),
        methodical_description = "Comece em uma posição de base, como a primeira posição. Estenda a perna para cima, mantendo a postura ereta e o centro do corpo firme. Mantenha o pé em pointe, com o pé ativo. Retorne a perna para a posição inicial com controle. O grand battement pode ser realizado em várias direções e velocidades.",
        child_explanation = "É como um battement tendu, mas você estende a perna bem alto, como se estivesse tentando tocar o teto com o pé."
    ),
    Movement(
        id = 27,
        name_official = "Fondu",
        synonyms = listOf("Fondue"),
        description = "Flexão da perna de apoio enquanto a outra está levantada.",
        grade = 2,
        complexity = 3,
        typo = "Fondu",
        translation = "Fundir",
        detailed_description = "O fondu é um movimento onde a perna de apoio se flexiona enquanto a outra perna está levantada. É um movimento de controle e força que requer coordenação e equilíbrio. O fondu é frequentemente usado em adagio e em algumas sequências de balé clássico.",
        related = listOf("Força", "Controle", "Coordenação", "Equilíbrio", "Pés", "Perna", "Adagio"),
        methodical_description = "Comece em uma posição de base, como a primeira posição. Levante uma perna e flexione a perna de apoio, mantendo o equilíbrio. Mantenha o corpo alinhado e o centro do corpo firme. Retorne à posição inicial com controle. O fondu pode ser realizado em várias direções e velocidades.",
        child_explanation = "Imagine que você está afundando em uma almofada com uma perna, enquanto a outra perna está levantada. É como um plié, mas você está dobrando apenas a perna que está no chão."
    ),
    Movement(
        id = 28,
        name_official = "Adagio",
        synonyms = listOf(),
        description = "Sequência de movimentos lentos e controlados, enfatizando a fluidez e a expressão.",
        grade = 2,
        complexity = 3,
        typo = "Adagio",
        translation = "Adagio",
        detailed_description = "O adagio é uma sequência de movimentos lentos e controlados, geralmente realizados com uma música suave. É um exercício que enfatiza a fluidez, a expressão e o controle do corpo. O adagio é usado para desenvolver a técnica, a flexibilidade e a força, além de melhorar a consciência corporal e a comunicação artística.",
        related = listOf("Controle", "Fluidez", "Expressão", "Técnica", "Flexibilidade", "Força", "Consciência Corporal"),
        methodical_description = "O adagio é geralmente realizado com uma música suave. As sequências variam, mas geralmente incluem pliés, port de bras, battements, rond de jambe e outros movimentos lentos e controlados. O foco está na beleza, na precisão e na expressão.",
        child_explanation = "É como uma dança lenta e elegante, onde você se move suavemente e expressa a música com seu corpo."
    ),
    Movement(
        id = 29,
        name_official = "Soubressaut",
        synonyms = listOf("Leap", "Jump"),
        description = "Salto onde o dançarino se eleva do chão e aterrissa na mesma posição, com um movimento leve e elástico.",
        grade = 2,
        complexity = 3,
        typo = "Soubressaut",
        translation = "Sobressalto",
        detailed_description = "O soubressaut é um salto onde o dançarino se eleva do chão e aterrissa na mesma posição, com um movimento leve e elástico. É um movimento de força e controle que requer coordenação e equilíbrio. O soubressaut é frequentemente usado em sequências de balé clássico e em danças de caráter.",
        related = listOf("Força", "Controle", "Coordenação", "Equilíbrio", "Salto", "Pernas", "Aterrissagem"),
        methodical_description = "Comece em uma posição de base. Salte com um movimento rápido e elástico, mantendo o corpo alinhado e aterrissando na mesma posição. O soubressaut pode ser realizado em várias direções e velocidades.",
        child_explanation = "É como um petit jeté, mas você se eleva mais alto e aterrissa com uma sensação de leveza e elasticidade. Imagine que você está pulando em um trampolim."
    ),
    Movement(
        id = 30,
        name_official = "Echappé",
        synonyms = listOf("Echappé"),
        description = "Movimento onde os pés se abrem de uma posição fechada para uma posição aberta.",
        grade = 2,
        complexity = 2,
        typo = "Echappé",
        translation = "Escapado",
        detailed_description = "O echappé é um movimento onde os pés se abrem de uma posição fechada para uma posição aberta. É um movimento de controle e coordenação que requer força e equilíbrio. O echappé é frequentemente usado em sequências de balé clássico e em danças de caráter.",
        related = listOf("Controle", "Coordenação", "Força", "Equilíbrio", "Pés", "Posições"),
        methodical_description = "Comece em uma posição fechada, como a primeira posição. Abra os pés para uma posição aberta, como a segunda posição. Mantenha o corpo alinhado e o centro do corpo firme. Retorne à posição fechada com controle. O echappé pode ser realizado em várias velocidades e níveis de elevação.",
        child_explanation = "É como se você estivesse abrindo as pernas de um abraço. Você abre os pés e depois os fecha novamente."
    ),
    Movement(
        id = 31,
        name_official = "Pas de Basque",
        synonyms = listOf("Basque Step"),
        description = "Movimento de três tempos onde o dançarino se move para frente e depois para trás.",
        grade = 2,
        complexity = 2,
        typo = "Pas de Basque",
        translation = "Passo Basco",
        detailed_description = "O pas de basque é um movimento de três tempos onde o dançarino se move para frente e depois para trás. É um movimento de coordenação e ritmo que requer controle e equilíbrio. O pas de basque é frequentemente usado em sequências de balé clássico e em danças de caráter.",
        related = listOf("Ritmo", "Coordenação", "Controle", "Equilíbrio", "Pés", "Movimento", "Danças de caráter"),
        methodical_description = "Comece em uma posição de base. Dê um passo para frente com um pé, depois traga o outro pé para a frente e junte-o ao primeiro pé. Finalmente, mova o primeiro pé para trás, completando o ciclo. O pas de basque pode ser realizado em várias velocidades e direções.",
        child_explanation = "Imagine que você está fazendo um pequeno passo para frente e depois para trás, como se estivesse dançando em um salão de baile."
    ),
    Movement(
        id = 32,
        name_official = "Battement Glissé",
        synonyms = listOf("Battement Glissé"),
        description = "Extensão da perna em direção ao chão, seguida de um deslizamento suave.",
        grade = 3,
        complexity = 2,
        typo = "Battement Glissé",
        translation = "Battement Deslizante",
        detailed_description = "O battement glissé é um movimento onde a perna é estendida em direção ao chão, e depois desliza suavemente para a posição inicial. É um exercício para desenvolver a flexibilidade, a força e o controle dos músculos das pernas e dos pés.",
        related = listOf("Flexibilidade", "Força", "Controle", "Pés", "Perna", "Deslizamento"),
        methodical_description = "Comece em uma posição de base, como a primeira posição. Estenda a perna em direção ao chão, mantendo o pé em contato com o solo. Deslize a perna suavemente de volta para a posição inicial. O battement glissé pode ser realizado em várias direções e velocidades.",
        child_explanation = "Imagine que você está deslizando o pé no chão, como se estivesse desenhando uma linha reta."
    ),
    Movement(
        id = 33,
        name_official = "Battement  Fondù",
        synonyms = listOf("Battement Fondù", "Battement Fondue"),
        description = "Extensão da perna, seguida de uma flexão suave da perna de apoio.",
        grade = 3,
        complexity = 2,
        typo = "Battement  Fondù",
        translation = "Battement Fundido",
        detailed_description = "O battement fondù é um movimento onde a perna é estendida, seguida de uma flexão suave da perna de apoio. É um exercício para desenvolver a flexibilidade, a força e o controle dos músculos das pernas e dos pés.",
        related = listOf("Flexibilidade", "Força", "Controle", "Pés", "Perna", "Flexão", "Fundido"),
        methodical_description = "Comece em uma posição de base, como a primeira posição. Estenda a perna para frente, lado ou trás. Flexione a perna de apoio com um movimento suave e controlado. Retorne à posição inicial. O battement fondù pode ser realizado em várias direções e velocidades.",
        child_explanation = "É como um battement tendu, mas você dobra a perna que está no chão ao mesmo tempo que estende a outra perna."
    ),
    Movement(
        id = 34,
        name_official = "Développé à la seconde",
        synonyms = listOf("Développé à la Seconde"),
        description = "Extensão da perna levantada para a posição de segunda posição, frente ou atrás.",
        grade = 3,
        complexity = 3,
        typo = "Développé à la seconde",
        translation = "Développé à la Seconde",
        detailed_description = "O développé à la seconde é um movimento onde a perna levantada é estendida para a posição de segunda posição, frente ou atrás. É um exercício avançado que requer flexibilidade, força e controle.",
        related = listOf("Flexibilidade", "Força", "Controle", "Pés", "Perna", "Segunda Posição", "Développé"),
        methodical_description = "Comece em uma posição de base, como a primeira posição. Levante uma perna para a frente, lado ou trás. Estenda a perna até que ela forme a segunda posição, mantendo o pé em pointe. Mantenha a postura ereta e o centro do corpo firme. Retorne a perna para a posição inicial com controle.",
        child_explanation = "É como um développé, mas você estende a perna até que ela fique bem na posição de segunda posição."
    ),
    Movement(
        id = 35,
        name_official = "Grand Battement  à la seconde",
        synonyms = listOf("Grand Battement à la Seconde"),
        description = "Extensão da perna levantada para a posição de segunda posição, frente ou atrás, com maior amplitude.",
        grade = 3,
        complexity = 4,
        typo = "Grand Battement  à la seconde",
        translation = "Grand Battement à la Seconde",
        detailed_description = "O grand battement à la seconde é um movimento onde a perna levantada é estendida para a posição de segunda posição, frente ou atrás, com maior amplitude do que o développé à la seconde. É um exercício avançado que requer grande flexibilidade, força e controle.",
        related = listOf("Flexibilidade", "Força", "Controle", "Pés", "Perna", "Segunda Posição", "Grand Battement", "Développé"),
        methodical_description = "Comece em uma posição de base, como a primeira posição. Levante uma perna para a frente, lado ou trás. Estenda a perna até que ela forme a segunda posição, mantendo o pé em pointe. Mantenha a postura ereta e o centro do corpo firme. Retorne a perna para a posição inicial com controle.",
        child_explanation = "É como um grand battement, mas você estende a perna até que ela fique bem na posição de segunda posição."
    ),
    Movement(
        id = 36,
        name_official = "Rond de Jambe à Terre",
        synonyms = listOf("Rond de Jambe à Terre"),
        description = "Círculo da perna no chão, frente ou atrás.",
        grade = 3,
        complexity = 2,
        typo = "Rond de Jambe à Terre",
        translation = "Círculo de Perna no Chão",
        detailed_description = "O rond de jambe à terre é um movimento onde a perna é movida em um círculo no chão, começando para frente e depois para trás, mantendo o pé em contato com o solo. É um exercício para desenvolver a flexibilidade e o controle dos músculos das pernas e dos pés.",
        related = listOf("Flexibilidade", "Controle", "Pés", "Perna", "Círculo"),
        methodical_description = "Comece em uma posição de base, como a primeira posição. Estenda a perna para frente, mantendo o pé em contato com o solo. Mova a perna em um círculo no chão, primeiro para frente, depois para trás, e depois para frente novamente. Mantenha a postura ereta e o centro do corpo firme. O rond de jambe à terre pode ser realizado em várias velocidades e níveis de amplitude.",
        child_explanation = "Imagine que você está desenhando um círculo no chão com o seu pé, sem levantar o pé do chão."
    ),
    Movement(
        id = 37,
        name_official = "Changement",
        synonyms = listOf("Changement"),
        description = "Salto onde os pés se cruzam no ar e aterrissam em posições invertidas.",
        grade = 3,
        complexity = 3,
        typo = "Changement",
        translation = "Mudança",
        detailed_description = "O changement é um salto onde os pés se cruzam no ar e aterrissam em posições invertidas. É um movimento de força e coordenação que requer controle e equilíbrio. O changement é frequentemente usado em sequências de balé clássico e em danças de caráter.",
        related = listOf("Força", "Controle", "Coordenação", "Equilíbrio", "Salto", "Pés", "Posições", "Cruzamento"),
        methodical_description = "Comece em uma posição de base, como a primeira posição. Salte e cruze os pés no ar, com o pé da frente se tornando o pé de trás e vice-versa. Mantenha o corpo alinhado e o centro do corpo firme. Aterrisse com os pés em posições invertidas. O changement pode ser realizado em várias velocidades e níveis de elevação.",
        child_explanation = "Imagine que você está pulando e cruzando os pés no ar, como se estivesse trocando as pernas de lugar."
    ),
    Movement(
        id = 38,
        name_official = "Glissade",
        synonyms = listOf("Glissade"),
        description = "Movimento de deslizamento onde a perna é estendida para a frente e depois para trás.",
        grade = 3,
        complexity = 2,
        typo = "Glissade",
        translation = "Deslizamento",
        detailed_description = "O glissade é um movimento de deslizamento onde a perna é estendida para a frente e depois para trás. É um exercício para desenvolver a flexibilidade, a força e o controle dos músculos das pernas e dos pés.",
        related = listOf("Flexibilidade", "Força", "Controle", "Pés", "Perna", "Deslizamento"),
        methodical_description = "Comece em uma posição de base, como a primeira posição. Estenda a perna para a frente, mantendo o pé em contato com o solo. Deslize a perna suavemente para trás, mantendo o corpo alinhado. O glissade pode ser realizado em várias velocidades e níveis de amplitude.",
        child_explanation = "Imagine que você está deslizando o pé no chão, como se estivesse desenhando uma linha reta."
    ),
    Movement(
        id = 39,
        name_official = "Sissonne",
        synonyms = listOf("Sissonne"),
        description = "Salto onde uma perna é levantada enquanto a outra permanece no chão.",
        grade = 3,
        complexity = 3,
        typo = "Sissonne",
        translation = "Sissonne",
        detailed_description = "A sissonne é um salto onde uma perna é levantada enquanto a outra permanece no chão. É um movimento de força e controle que requer coordenação e equilíbrio. A sissonne é frequentemente usada em sequências de balé clássico e em danças de caráter.",
        related = listOf("Força", "Controle", "Coordenação", "Equilíbrio", "Salto", "Pés", "Posições"),
        methodical_description = "Comece em uma posição de base, como a primeira posição. Salte e levante uma perna, mantendo a outra perna no chão. Mantenha o corpo alinhado e o centro do corpo firme. Aterrisse com os pés na posição inicial. A sissonne pode ser realizada em várias direções e níveis de elevação.",
        child_explanation = "Imagine que você está pulando e levantando uma perna, enquanto a outra perna fica no chão. É como um salto onde você coloca uma perna para cima e a outra para baixo."
    ),
    Movement(
        id = 40,
        name_official = "Assemblé",
        synonyms = listOf("Assemblé"),
        description = "Salto onde os pés se juntam no ar e aterrissam juntos.",
        grade = 3,
        complexity = 3,
        typo = "Assemblé",
        translation = "Juntar",
        detailed_description = "O assemblé é um salto onde os pés se juntam no ar e aterrissam juntos. É um movimento de força e coordenação que requer controle e equilíbrio. O assemblé é frequentemente usado em sequências de balé clássico e em danças de caráter.",
        related = listOf("Força", "Controle", "Coordenação", "Equilíbrio", "Salto", "Pés", "Posições"),
        methodical_description = "Comece em uma posição de base, como a primeira posição. Salte e junte os pés no ar. Mantenha o corpo alinhado e o centro do corpo firme. Aterrisse com os pés juntos. O assemblé pode ser realizado em várias direções e níveis de elevação.",
        child_explanation = "Imagine que você está pulando e juntando os pés no ar, como se estivesse fazendo um abraço com os pés."
    ),
    Movement(
        id = 41,
        name_official = "Temps Lévé",
        synonyms = listOf("Temps Lévé"),
        description = "Movimento de três tempos onde o dançarino se eleva no ar, com uma perna estendida.",
        grade = 3,
        complexity = 3,
        typo = "Temps Lévé",
        translation = "Tempo Elevado",
        detailed_description = "O temps levé é um movimento de três tempos onde o dançarino se eleva no ar, com uma perna estendida. É um movimento de força e coordenação que requer controle e equilíbrio. O temps levé é frequentemente usado em sequências de balé clássico e em danças de caráter.",
        related = listOf("Força", "Controle", "Coordenação", "Equilíbrio", "Salto", "Pés", "Perna", "Posições"),
        methodical_description = "Comece em uma posição de base, como a primeira posição. Dê um passo com um pé, e depois eleve a outra perna, enquanto se eleva no ar. Aterrisse com os pés na posição inicial. O temps levé pode ser realizado em várias direções e níveis de elevação.",
        child_explanation = "Imagine que você está pulando e levantando uma perna, enquanto a outra perna fica no chão. É como um salto onde você coloca uma perna para cima e a outra para baixo."
    ),
    Movement(
        id = 42,
        name_official = "Posé",
        synonyms = listOf("Posé"),
        description = "Movimento onde a perna é levantada e abaixada suavemente, com o pé em pointe.",
        grade = 3,
        complexity = 2,
        typo = "Posé",
        translation = "Posado",
        detailed_description = "O posé é um movimento onde a perna é levantada e abaixada suavemente, com o pé em pointe. É um exercício para desenvolver a flexibilidade, a força e o controle dos músculos das pernas e dos pés.",
        related = listOf("Flexibilidade", "Força", "Controle", "Pés", "Perna", "Pointe", "Posado"),
        methodical_description = "Comece em uma posição de base, como a primeira posição. Levante uma perna, mantendo o pé em pointe. Abaixe a perna suavemente de volta para a posição inicial. O posé pode ser realizado em várias direções e velocidades.",
        child_explanation = "Imagine que você está colocando a perna para cima e para baixo, como se estivesse colocando um objeto delicado em um pedestal."
    ),
    Movement(
        id = 43,
        name_official = "Grand Allegro",
        synonyms = listOf("Grand Allegro"),
        description = "Sequência de saltos grandes e poderosos, com um alto nível de energia e técnica.",
        grade = 3,
        complexity = 4,
        typo = "Grand Allegro",
        translation = "Grande Allegro",
        detailed_description = "O grand allegro é uma sequência de saltos grandes e poderosos, com um alto nível de energia e técnica. É um exercício avançado que requer grande força, flexibilidade, coordenação e controle. O grand allegro é frequentemente usado em sequências de balé clássico e em danças de caráter.",
        related = listOf("Força", "Flexibilidade", "Controle", "Coordenação", "Saltos", "Pés", "Perna", "Técnica", "Energia"),
        methodical_description = "O grand allegro é geralmente realizado com música rápida e energética. As sequências variam, mas geralmente incluem saltos como assemblé, sissone, grand jeté, e outros saltos grandes e poderosos. O foco está na altura, na precisão, na força e na expressão.",
        child_explanation = "É como uma dança rápida e emocionante, onde você salta alto e faz movimentos grandiosos. Imagine que você está voando no ar!"
    )
)
